---
title: "Analysis of USDA Income forecast Errors"
author: Lawson Connor
Date: 4/9/2018
output: pdf_document
header-includes:
- \usepackage[margin=1in]{geometry}
- \usepackage{graphicx}
- \usepackage{epstopdf}
- \usepackage{booktabs}
- \usepackage{amsmath}
- \usepackage{tabularx}
- \usepackage{caption}
- \usepackage{makecell}
- \usepackage{array}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(stargazer)
library(strucchange)
```

```{r load_scripts, include = FALSE}
source('./forecast_plots.R')
source('./error_temporal_patterns_log.R')
```

```{r, echo= FALSE}
index <- which(str_detect(colnames(inc_fcst),"Net"))                                   # Catches the variable attached to the final cash/farm income estimate
income_estimate <- log(inc_fcst[[index]])

############################################################################################

# Revision Variable Gen -----------------------------------------------------------
inc_fcst <- mutate(inc_fcst, 
                   aug_rev = (`August forecast` - `February forecast`)/`February forecast`,                              # Change in August update on February forecast
                   nov_rev = (`November forecast` - `August forecast`)/`August forecast`,                                # Change in November update on August forecast
                   feb_rev = (`February(t+1) forecast` - `November forecast`)/`November forecast`,                       # Change in February(t+1) update on November forecast 
                   aug_est = (`August (t + 1) "estimate"` - `February(t+1) forecast`)/`February(t+1) forecast`,          # Change in August first estimate on February(t+1) forecast
                   final_est = (income_estimate - `August (t + 1) "estimate"`)/`August (t + 1) "estimate"`)              # Change in final estimate on August(t+1) estimate

# Generate Forecast Error -------------------------------------------------------------
inc_fcst %<>%
  mutate(ehat_feb = income_estimate - log(`February forecast`),
         ehat_aug = income_estimate - log(`August forecast`),
         ehat_nov = income_estimate - log(`November forecast`),
         ehat_feb1 = income_estimate - log(`February(t+1) forecast`),
         ehat_init = income_estimate - log(`August (t + 1) "estimate"`),
         dif = income_estimate - lead(income_estimate),
         t = `Reference Year` - 1974,
         t2 = t^2,
         t3 = t^3,
         t4 = t^4)
  

# Forecast Accuracy ----------------------------------------------------------------

#############################################################################################################
#Remember to comment out when running the farm income file. Include when running cash income file
inc_fcst$`August (t + 1) "estimate"`[is.na(inc_fcst$`August (t + 1) "estimate"`)] <- income_estimate[is.na(inc_fcst$`August (t + 1) "estimate"`)]

#############################################################################################################
# Plot trend to visually inspect best fit
ggplot(inc_fcst, aes(y = income_estimate , x = `Reference Year`)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = lm, formula = y ~ x)

# Estimate the linear trend and get predicted trend values. 
l_trnd <- lm(income_estimate ~ t, data = inc_fcst)
summary(l_trnd)

inc_fcst$yhat <- predict(l_trnd, inc_fcst)
inc_fcst$var <- l_trnd$resid^2

# Produce indicator variables for large negative and positive estimates.
inc_fcst <- inc_fcst %>%
  mutate(delta = income_estimate - yhat,
         deviation = income_estimate - yhat,
         var = deviation^2,
         large = factor(delta > 0.1),
         small = factor(delta < -0.1))
#############################################################################################################
# Behavior of Variance of Income over time
vrc <- lm(var ~ `Reference Year`, data = inc_fcst)
summary(vrc)

#############################################################################################################
# Structural Breaks in Farm Income estimates
inc_fcst <- inc_fcst %>%
  arrange(`Reference Year`)

index <- which(str_detect(colnames(inc_fcst),"Net"))                                   # Catches the variable attached to the final cash/farm income estimate
income_estimate <- inc_fcst[[index]]

incomes <- ts(income_estimate, start = c(1975, 1), end = c(2016, 1), frequency = 1)

bp <- breakpoints(incomes ~ 1, data = inc_fcst)
summary(bp)

#plot(bp)
plot(incomes)
lines(bp)

ci_incomes <- confint(bp)
lines(ci_incomes)

# Time Dependence of Forecast Error Bias
fit <- list()                                                 # Create vector for lm() output
tile <- which(str_detect(colnames(inc_fcst),"ehat"))          # Extract column indexes with forecast error variables in the inc_fcst tibble

for (i in seq_along(tile)){
  
  eht_idx <- tile[i]                                            # Get column index of forecast variables from tile 
  fit[[i]] <- lm(inc_fcst[[eht_idx]]~ t, data = inc_fcst)        # Perform intercept regression on each forecast error column. Put output into fit
  
}

fit %>%                                                       
  map(summary)                                                # Iterate through the columns of fit to summarize the output from lm()

```



```{r mylatextable, results = "asis"}
stargazer(stargazer(fit, title = "Time Dependence of Forecast Error Bias",
          dep.var.labels = c("February Forecast", "August Forecast", 
                             "November Forecast", "February (t+1) Forecast", 
                             "August (t+1) Estimate"), type = 'latex'))
```